[project]
authors = ["Mike Müller <mmueller@python-academy.de>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pysv_website"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
lektor = "*"
ca-certificates = "*"
certifi = "*"
openssl = "*"
jinja2 = "*"
markupsafe = "*"
flask = ">=2.1.0"
pip = "*"

[pypi-dependencies]
python-avatars = "*"
